"""add expire_date to products table

Revision ID: dc343dbea5ab
Revises: b27fa98c876f
Create Date: 2025-07-24 06:49:41.211482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc343dbea5ab'
down_revision: Union[str, Sequence[str], None] = 'b27fa98c876f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'key',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('products', sa.Column('expire_date', sa.Date(), nullable=True))
    op.alter_column('products', 'image_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'image_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('products', 'expire_date')
    op.alter_column('images', 'key',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
